#
# BTstack example 'hfp_hf_demo' for ESP32 port
#
# Generated by /Users/chrisgreening/esp/btstack/port/esp32
# On Fri Jul 23 14:34:42 2021

PROJECT_NAME := hfp_hf_demo

include $(IDF_PATH)/make/project.mk
